language: objective-c
os: osx
osx_image: xcode9.4
env:
  - XCWORKSPACE=MessagePack.xcworkspace XCPROJECT=MessagePack.xcodeproj XCSCHEME=MessagePack-Package
script:
  - xctool -workspace $XCWORKSPACE -scheme $XCSCHEME run-tests
